import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "sahildmk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="bg-gradient-to-tr from-neutral-900 to-neutral-950 via-neutral-800 sm:via-65% via-60%"
    >
      <body className={GeistSans.className}>{children}</body>
    </html>
  );
}
